server {
	listen 8001;
	host 127.0.0.1;
	server_name amiwuevo;
	error_page 403 ./www/amiwuevo/error/403.html;
	error_page 404 ./www/amiwuevo/error/404.html;
	error_page 405 ./www/amiwuevo/error/405.html;
	error_page 500 ./www/amiwuevo/error/500.html;
	root ./www/amiwuevo;
	index ./www/amiwuevo/index.html;
	client_max_body_size 100Mb;
	#Can define URL as URL /amiwuevo to redirect to /tmp/www
	#Can define a default page when the url requested is a directory, I think that's teh root

	#Location can have a storage location for files using POST in client side
	location / {
		allow_methods GET POST DELETE;
		autoindex on;
		index ./www/amiwuevo/index.html;
		upload ./www/amiwuevo/upload;
	}

	location /error {}

	#Enable and disable dirctory listing - this is the autoindex option
	location /images {
		root ./www/amiwuevo;
		autoindex off;
		}

	#Need to read the cgi's stuff better
	location /cgi-bin {
		root ./www/amiwuevo/cgi-bin;
		cgi_path /usr/bin/python3 ./www/amiwuevo/cgi-bin/;
		cgi_ext .py;
	}
}

#We'll need an additional server for another page