server {
      listen 8080;
      host 127.3;
      server_name amiwuevo;
      error_page 404 ./www/amiwuevo/error/404.html;
      client_max_body_size 100Mb;
      root ./www/amiwuevo;
      index ./www/amiwuevo/index.html;

      location / {
          allow_methods GET POST DELETE;
          autoindex on;
          index ./www/amiwuevo/index.html;
          upload ./www/amiwuevo/upload;
	  }

      location /error {}

      location /images {
          root ./www/amiwuevo/images;
          autoindex on;
          protected off;
      }

      location /cgi-bin {
          root ./www/amiwuevo/cgis;
          cgi_path /usr/bin/python3 ./www/amiwuevo/cgi-bin/;
          cgi_ext .py;
      }
}

#We'll need an additional server for another page